title: 판다치의 대나무 하우스
desciption: >
  pandachi's bamboo house.
email: pthpp200@naver.com
baseurl: "/" # the subpath of your site, e.g. /blog
#replace nrdybhu1.github.io with your domainname.com
url: "https://pandachi31.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  pandachi31
markdown: kramdown
page_excerpts: true
favicon: "bamboo.png"
collections:
  posts:
    permalink: "/blog/:title:output_ext"
    output: true
defaults:
- scope:
    path: _posts
    type: posts
- scope:
    path: ''
  values:
    image: "/img/preview.png"
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-redirect-from
- jemoji
- jekyll-paginate

paginate: 5
paginate_path: "/blog/page-:num/"
